//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLoveSharePoint.Fields.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iLoveSharePoint_Fields_LookupFieldWithPicker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iLoveSharePoint_Fields_LookupFieldWithPicker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iLoveSharePoint.Fields.Resources.iLoveSharePoint.Fields.LookupFieldWithPicker", typeof(iLoveSharePoint_Fields_LookupFieldWithPicker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable columns:.
        /// </summary>
        internal static string lookupWithPickerChooseSearchFieldsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerChooseSearchFieldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLove SharePoint - Lookup with Picker.
        /// </summary>
        internal static string lookupWithPickerDescription {
            get {
                return ResourceManager.GetString("lookupWithPickerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup with Picker.
        /// </summary>
        internal static string lookupWithPickerDisplayName {
            get {
                return ResourceManager.GetString("lookupWithPickerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity rows (applies to multiselect mode):.
        /// </summary>
        internal static string lookupWithPickerEntityRowsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerEntityRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal search results:.
        /// </summary>
        internal static string lookupWithPickerMaxSearchResultsLabel {
            get {
                return ResourceManager.GetString("lookupWithPickerMaxSearchResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        internal static string lookupWithPickerOperatorBeginsWith {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string lookupWithPickerOperatorContains {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string lookupWithPickerOperatorEquals {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than.
        /// </summary>
        internal static string lookupWithPickerOperatorGreaterThan {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than or equal to.
        /// </summary>
        internal static string lookupWithPickerOperatorGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        internal static string lookupWithPickerOperatorLessThan {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than or equal to.
        /// </summary>
        internal static string lookupWithPickerOperatorLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equal.
        /// </summary>
        internal static string lookupWithPickerOperatorNotEqual {
            get {
                return ResourceManager.GetString("lookupWithPickerOperatorNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum count of search results has been exeeded. Please refine your search..
        /// </summary>
        internal static string lookupWithPickerSearchResultExceededMessage {
            get {
                return ResourceManager.GetString("lookupWithPickerSearchResultExceededMessage", resourceCulture);
            }
        }
    }
}
