//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.WFDataExchange {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowExternalData", Namespace="http://iLoveSharePoint.com/Workflow/Activities/Services/Data")]
    [System.SerializableAttribute()]
    public partial class WorkflowExternalData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationToken {
            get {
                return this.CorrelationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationTokenField, value) != true)) {
                    this.CorrelationTokenField = value;
                    this.RaisePropertyChanged("CorrelationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowId {
            get {
                return this.WorkflowIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowIdField, value) != true)) {
                    this.WorkflowIdField = value;
                    this.RaisePropertyChanged("WorkflowId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iLoveSharePoint.com/Workflow/Activities/Services", ConfigurationName="WFDataExchange.IExternalWorkflowDataService")]
    public interface IExternalWorkflowDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iLoveSharePoint.com/Workflow/Activities/Services/IExternalWorkflowDataServ" +
            "ice/SendDataToWorkflow", ReplyAction="http://iLoveSharePoint.com/Workflow/Activities/Services/IExternalWorkflowDataServ" +
            "ice/SendDataToWorkflowResponse")]
        void SendDataToWorkflow(TestConsole.WFDataExchange.WorkflowExternalData externalData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExternalWorkflowDataServiceChannel : TestConsole.WFDataExchange.IExternalWorkflowDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalWorkflowDataServiceClient : System.ServiceModel.ClientBase<TestConsole.WFDataExchange.IExternalWorkflowDataService>, TestConsole.WFDataExchange.IExternalWorkflowDataService {
        
        public ExternalWorkflowDataServiceClient() {
        }
        
        public ExternalWorkflowDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalWorkflowDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalWorkflowDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalWorkflowDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendDataToWorkflow(TestConsole.WFDataExchange.WorkflowExternalData externalData) {
            base.Channel.SendDataToWorkflow(externalData);
        }
    }
}
